pipeline:
  # lint:
  #   image: ubuntu-latest
  #   when:
  #     event: [push, tag, deployment]
  #   commands:
  #     - apt update && apt install git python3
  #     - python3 -m ensurepip
  #     - python3 -m pip install virtualenv

  build:
    image: ubuntu:latest
    when:
      tag: v*
    commands:
        - ls
        - pwd
        - apt update && apt install -y git python3
        - curl -fsSL https://get.docker.com/ | sh
        - cd busfs-server
        - docker build -t codeberg.org/m3r/busfs-server:latest . && docker login codeberg.org -u m3r -p $DOCKER_PASSWORD && docker push codeberg.org/m3r/busfs-server:latest
